export const audioMap = {
  "Ravi has 3 point 4 5 dollars. The toy costs 3 point 5 zero dollars. Does Ravi have enough money?": "/assets/audio/audio_question_ravi_has_3_point_4_5_dollars_the_toy_costs_3_point_0.mp3",
  "When numbers have a decimal point, even a tiny difference matters! Let's explore what those digits mean.": "/assets/audio/audio_statement_when_numbers_have_a_decimal_point_even_a_tiny_diff_1.mp3",
  "The difference is just 5 cents — but which number is bigger?": "/assets/audio/audio_thinking_the_difference_is_just_5_cents_but_which_number_is_2.mp3",
  "A ribbon is 2 point 6 meters long. Another is 2 point zero 6 meters. Which ribbon is longer?": "/assets/audio/audio_question_a_ribbon_is_2_point_6_meters_long_another_is_2_poi_3.mp3",
  "Both look similar, but they are actually very different lengths!": "/assets/audio/audio_statement_both_look_similar_but_they_are_actually_very_diffe_4.mp3",
  "The digits after the decimal point decide — tenths vs hundredths!": "/assets/audio/audio_instruction_the_digits_after_the_decimal_point_decide_tenths_v_5.mp3",
  "A weighing scale shows 4 point zero 8 kilograms. What does the 8 mean?": "/assets/audio/audio_question_a_weighing_scale_shows_4_point_zero_8_kilograms_wh_6.mp3",
  "Every digit in a decimal number has its own special place and value!": "/assets/audio/audio_statement_every_digit_in_a_decimal_number_has_its_own_specia_7.mp3",
  "Is it 8 tenths? Or 8 hundredths? The position tells all!": "/assets/audio/audio_instruction_is_it_8_tenths_or_8_hundredths_the_position_tells__8.mp3",
  "Priya scores 9 point 7 zero and Ahmad scores 9 point 7. Who scored higher?": "/assets/audio/audio_question_priya_scores_9_point_7_zero_and_ahmad_scores_9_poi_9.mp3",
  "Are these two scores the same, or is one really higher?": "/assets/audio/audio_statement_are_these_two_scores_the_same_or_is_one_really_hig_10.mp3",
  "Do trailing zeros change the value? Let's find out!": "/assets/audio/audio_instruction_do_trailing_zeros_change_the_value_let_s_find_out_11.mp3",
  "A bus fare costs 1 point zero 5 dollars and a snack costs zero point 9 zero dollars. Together, how much?": "/assets/audio/audio_question_a_bus_fare_costs_1_point_zero_5_dollars_and_a_snac_12.mp3",
  "Decimals help us count money exactly — every cent matters!": "/assets/audio/audio_statement_decimals_help_us_count_money_exactly_every_cent_ma_13.mp3",
  "Can you add decimals like whole numbers? Almost — but you must line up the dots!": "/assets/audio/audio_instruction_can_you_add_decimals_like_whole_numbers_almost_but_14.mp3",
  "Leo really wants the new toy robot in the shop window. The price tag says 12 point 5 zero dollars. The number before the dot tells him the whole dollars, and the numbers after the dot are the parts of a dollar — the cents! Decimals help us count money perfectly.": "/assets/audio/audio_statement_leo_really_wants_the_new_toy_robot_in_the_shop_win_15.mp3",
  "Later, Leo helps his mom bake a cake. The recipe needs exactly 1 point 2 5 kilograms of flour. The 2 is in the tenths place, and the 5 is in the hundredths place. Every tiny bit matters in baking, and decimals help us measure exactly what we need!": "/assets/audio/audio_statement_later_leo_helps_his_mom_bake_a_cake_the_recipe_nee_16.mp3",
  "At school, Leo runs a race in 14 point 8 seconds. His friend runs it in 14 point zero 8 seconds. Who was faster? 14 point 8 has 8 tenths, but 14 point zero 8 has zero tenths! So Leo took more time. His friend was faster!": "/assets/audio/audio_statement_at_school_leo_runs_a_race_in_14_point_8_seconds_hi_17.mp3",
  "In art class, Leo needs a ribbon exactly 3 point 5 meters long. He cuts a ribbon that is 3 point 5 zero meters long. His teacher smiles and says they are exactly the same length! Adding a zero at the end doesn't change the value.": "/assets/audio/audio_statement_in_art_class_leo_needs_a_ribbon_exactly_3_point_5__18.mp3",
  "Leo gets an A on his math quiz! He realizes decimals aren't just numbers on a page — they are everywhere in the real world, helping us measure things perfectly. Now, he's a true Decimal Explorer!": "/assets/audio/audio_celebration_leo_gets_an_a_on_his_math_quiz_he_realizes_decimal_19.mp3",
  "Welcome to the world of Decimals!": "/assets/audio/audio_celebration_welcome_to_the_world_of_decimals_20.mp3",
  "Let's build numbers! Drag the discs into the correct column to show the ones, tenths, and hundredths.": "/assets/audio/audio_instruction_let_s_build_numbers_drag_the_discs_into_the_correc_21.mp3",
  "Amazing! You built it perfectly! Let's go to the next round!": "/assets/audio/audio_celebration_amazing_you_built_it_perfectly_let_s_go_to_the_nex_22.mp3",
  "Woohoo! Station one is complete! Now let's head to the Juice Mixing Lab!": "/assets/audio/audio_celebration_woohoo_station_one_is_complete_now_let_s_head_to_t_23.mp3",
  "Great work mixing! Time to mine some decimal crystals!": "/assets/audio/audio_celebration_great_work_mixing_time_to_mine_some_decimal_crysta_24.mp3",
  "You are a true Decimal Explorer! All three stations done!": "/assets/audio/audio_celebration_you_are_a_true_decimal_explorer_all_three_stations_25.mp3",
  "Choose the correct answer for the question.": "/assets/audio/audio_instruction_choose_the_correct_answer_for_the_question_26.mp3",
  "That's correct! Well done!": "/assets/audio/audio_celebration_that_s_correct_well_done_27.mp3",
  "Not quite! Try again — you can do it!": "/assets/audio/audio_encouragement_not_quite_try_again_you_can_do_it_28.mp3",
  "Great job! Let's review what you learned.": "/assets/audio/audio_celebration_great_job_let_s_review_what_you_learned_29.mp3",
  "Now let's test what you know. Can you teach it back?": "/assets/audio/audio_instruction_now_let_s_test_what_you_know_can_you_teach_it_back_30.mp3",
  "That's correct! You really understand decimals!": "/assets/audio/audio_celebration_that_s_correct_you_really_understand_decimals_31.mp3",
  "Almost! Remember what we learned — give it another try!": "/assets/audio/audio_encouragement_almost_remember_what_we_learned_give_it_another_tr_32.mp3"
};
